fix: Improve Darwin AMD64 build workflow structure and fix naming
initia-labs/initia pull request #328
Opened 2024-12-24 22:00 UTC by crStiv

# Description

This PR improves the build workflow for Darwin AMD64 by:
1. Fixing the typo in step name (ADM64 -> AMD64)
2. Restructuring the build commands for better readability and maintenance
3. Adding descriptive comments for each build step
4. Improving file handling with proper directory creation and cleanup

No functional changes are introduced, only code organization and naming improvements.

Closes: N/A

## Author Checklist

I have...

- [x] confirmed `!` is not needed as this is not an API breaking change
- [x] targeted the correct branch
- [x] provided a link to the relevant issue or specification (N/A - maintenance improvement)
- [x] reviewed "Files changed" and left comments if necessary
- [x] included the necessary unit and integration tests (N/A - workflow changes only)
- [x] updated the relevant documentation including comments
- [x] confirmed all CI checks have passed

## Reviewers Checklist

I have...

- [ ] confirmed the correct type prefix in the PR title
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic, API design and naming, documentation is accurate, tests and test coverage

2025-01-02 02:55 UTC, beer-1 requested changes
Thanks for your contribution, overall works LGTM but good to have one minor change.

2025-01-02 02:55 UTC, beer-1 commented on .github/workflows/build-darwin-amd64.yml
> +          cp "${HOME}/go/pkg/mod/github.com/initia-labs/movevm@${MOVEVM_VERSION}/api/libmovevm.dylib" build/
I think better to use `$(go env GOPATH)` instead of `${HOME}/go`

2025-01-03 09:07 UTC, beer-1 approved these changes
LGTM

2025-01-03 09:09 UTC, Vritra4 approved these changes
LGTM

2025-01-03 09:10 UTC, merged